apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer
spec:
  containers:
    - name: kafka-consumer
      image: kafka-consumer:v1
      imagePullPolicy: Never
      env:
      - name: "PYTHONUNBUFFERED"
        value: "0"
      - name: "BOOTSTRAP_SERVERS"
        value: "kafka-headless:9092"
