apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
spec:
  containers:
    - name: kafka-producer
      image: kafka-producer:v1
      imagePullPolicy: Never
      env:
      - name: "PYTHONUNBUFFERED"
        value: "0"
      - name: "BOOTSTRAP_SERVERS"
        value: "kafka-headless:9092"
