apiVersion: v1
kind: Secret
metadata:
  name: load-definition
type: Opaque
stringData:
  load_definition.json: |-
    {
      "vhosts":[{"name":"/"}],
      "users":[
        {"name":"user","password_hash":"2dLd5a8UVoxq/iegDUgMfHeX1q+PQIZndfBoiNarG5XCcPIg","hashing_algorithm":"rabbit_password_hashing_sha256","tags":"administrator"}
      ],
      "permissions":[
        {"user":"user","vhost":"/","configure":".*","write":".*","read":".*"}
      ],
      "queues":[{
        "name":"playground",
        "vhost":"/",
        "durable":true,
        "auto_delete":false,
        "arguments":{}
      }]
    }